using System.Diagnostics;
using System.Text;

namespace SiteShield.Services;

public sealed class HostsBlocker
{
    private const string MarkerStart = "# SITESHIELD START";
    private const string MarkerEnd = "# SITESHIELD END";
    private readonly string _hostsPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System), "drivers", "etc", "hosts");

    public void Apply(IEnumerable<string> allowedDomains)
    {
        var domains = allowedDomains.Select(NormalizeDomain).Where(x => x.Length > 0).Distinct(StringComparer.OrdinalIgnoreCase).ToList();
        var original = File.Exists(_hostsPath) ? File.ReadAllText(_hostsPath) : string.Empty;
        var cleaned = RemoveManagedSection(original);
        var sb = new StringBuilder(cleaned.TrimEnd());
        sb.AppendLine();
        sb.AppendLine(MarkerStart);
        sb.AppendLine("# Generated by SiteShield. Every domain not explicitly allowed below is blocked.");
        foreach (var domain in domains)
        {
            sb.AppendLine($"0.0.0.0 {domain}");
            sb.AppendLine($"0.0.0.0 www.{domain}");
        }
        sb.AppendLine(MarkerEnd);
        File.WriteAllText(_hostsPath, sb.ToString() + Environment.NewLine);
        FlushDns();
    }

    public void Disable()
    {
        if (!File.Exists(_hostsPath)) return;
        File.WriteAllText(_hostsPath, RemoveManagedSection(File.ReadAllText(_hostsPath)).TrimEnd() + Environment.NewLine);
        FlushDns();
    }

    private string RemoveManagedSection(string text)
    {
        var start = text.IndexOf(MarkerStart, StringComparison.OrdinalIgnoreCase);
        if (start < 0) return text;
        var end = text.IndexOf(MarkerEnd, start, StringComparison.OrdinalIgnoreCase);
        if (end < 0) return text[..start];
        end += MarkerEnd.Length;
        return text.Remove(start, end - start);
    }

    private static string NormalizeDomain(string domain)
    {
        domain = domain.Trim().ToLowerInvariant();
        domain = domain.Replace("https://", string.Empty).Replace("http://", string.Empty);
        domain = domain.Split('/')[0];
        domain = domain.Trim('.');
        if (domain.StartsWith("www.", StringComparison.OrdinalIgnoreCase)) domain = domain[4..];
        return domain;
    }

    private static void FlushDns()
    {
        try
        {
            using var p = Process.Start(new ProcessStartInfo
            {
                FileName = "ipconfig.exe",
                Arguments = "/flushdns",
                UseShellExecute = false,
                CreateNoWindow = true
            });
            p?.WaitForExit(5000);
        }
        catch { }
    }
}
